# Generated by Django 3.2.3 on 2021-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods_api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mood_tag',
            field=models.IntegerField(null=True),
        ),
    ]
