# Generated by Django 3.2.3 on 2021-05-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods_api', '0004_comment_mood_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
